# coding: utf-8

"""
    Coffee Shop API

    A simple API for managing coffee drinks.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.coffees_api import router as CoffeesApiRouter

app = FastAPI(
    title="Coffee Shop API",
    description="A simple API for managing coffee drinks.",
    version="1.0.0",
)

app.include_router(CoffeesApiRouter)
